---
# Build organization
- name: organization.yml - Create organization object
  ansible.controller.organization:
    name: "{{ organization }}"
    description: "{{ description }}"
    state: present
