---
# Build organization
- name: organization.yml - Create organization object
  ansible.controller.organization:
    name: "{{ organization }}"
    description: "{{ description }}"
    state: present
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: false
  ignore_errors: true
